# Generated by Django 5.2.1 on 2025-05-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thestore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
        migrations.AlterModelTable(
            name='producttypes',
            table='product_types',
        ),
        migrations.AlterModelTable(
            name='stores',
            table='stores',
        ),
        migrations.AlterModelTable(
            name='storetypes',
            table='store_types',
        ),
    ]
