# Generated by Django 5.2.1 on 2025-06-15 17:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thestore', '0002_alter_products_table_alter_producttypes_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=100)),
                ('password', models.BinaryField()),
                ('password_salt', models.BinaryField()),
                ('gender', models.CharField(max_length=1, null=True)),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(verbose_name=11)),
                ('is_acc_deleted', models.BooleanField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_done', models.BooleanField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(null=True)),
                ('updated_by', models.CharField(max_length=255)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_products', to='thestore.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_users', to='thestore.users')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
