# Generated by Django 5.2.1 on 2025-07-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thestore', '0003_users_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttypes',
            options={'verbose_name': 'Product Type', 'verbose_name_plural': 'Product Types'},
        ),
        migrations.AlterModelOptions(
            name='storetypes',
            options={'verbose_name': 'Store Type', 'verbose_name_plural': 'Store Types'},
        ),
        migrations.AddField(
            model_name='orders',
            name='created_by',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='created_by',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_by',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stores',
            name='created_by',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='stores',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
