# Generated by Django 5.2.1 on 2025-07-08 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thestore', '0004_alter_producttypes_options_alter_storetypes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders_products', to='thestore.products'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders_users', to='thestore.users'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_type',
            field=models.ForeignKey(db_column='product_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='products_product_types', to='thestore.producttypes'),
        ),
        migrations.AlterField(
            model_name='products',
            name='store_id',
            field=models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, related_name='products_stores', to='thestore.stores'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='store_types',
            field=models.ForeignKey(db_column='store_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='stores_store_types', to='thestore.storetypes'),
        ),
    ]
