networks:
  project-ecom-local:
    name: project-ecom-local
    driver: bridge

services:
  # Postgres database image
  project-ecom-db:
    image: postgres:latest
    container_name: ecom-db
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGPORT: ${DATABASE_PORT}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project-ecom-local

volumes:
  postgres_data: