networks:
  project-ecom-local:
    name: project-ecom-local
    driver: bridge

services:
  # Postgres database image
  project-ecom-db:
    image: postgres:latest
    container_name: ecom-db
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGPORT: ${DATABASE_PORT}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}' #extrnl:intrnl
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project-ecom-local

  # Django server
  project-ecom-admin:
    build:
      context: ./apps/db/ecomadmin/ecommerce
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./apps/db/ecomadmin/ecommerce:/code
    ports:
      - "8000:8000"
    depends_on:
      - project-ecom-db
    environment:
      - DB_NAME=${DATABASE_NAME}
      - DB_USER=${DATABASE_USERNAME}
      - DB_PASSWORD=${DATABASE_PASSWORD}
      - DB_HOST=${DOCKERIZED_DATABASE_HOST}
    networks:
      - project-ecom-local

volumes:
  postgres_data: