networks:
  project-ecom-local:
    name: project-ecom-local
    driver: bridge

services:
  # Postgres database container
  project-ecom-db:
    image: postgres:latest
    container_name: store-db
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      # PGPORT: ${DATABASE_PORT}
    ports:
      - '${DATABASE_EXTERNAL_PORT}:${DATABASE_PORT}' #extrnl:intrnl
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project-ecom-local

  # Django server container
  project-ecom-admin:
    build:
      context: ./apps/db/ecomadmin/ecommerce
    command: python manage.py runserver 0.0.0.0:8000
    container_name: store-db-admin
    volumes:
      - ./apps/db/ecomadmin/ecommerce:/code
    ports:
      - "8000:8000"
    depends_on:
      - project-ecom-db
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    networks:
      - project-ecom-local
volumes:
  postgres_data: